version: '3.4'

services:
  nginx:
    image: nginx:1.17-alpine
    restart: always
    volumes:
      - .:/var/www/html/:ro
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./logs/nginx:/var/log/nginx
    volumes_from:
      - php
    ports:
      - 80:80
      - 443:443
    links:
      - php
    container_name: con-nginx

  php-fpm:
    build: docker/php
    restart: always
    working_dir: /app
    volumes_from:
      - data
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    ports:
      - 9000:9000
    links:
      - mysql
    container_name: con-php-fpm

  mysql:
    image: mysql:5.7
    command: mysqld --max_allowed_packet=1024M
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root@123
        MYSQL_USER: root
        MYSQL_PASSWORD: root@123
    volumes:
      - ./.data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    container_name: con-db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - mysql:db
    container_name: con-adminer
